spring:
   datasource:
      username: nfl_teams
      password: nfl_teams
      url: jdbc:mysql://localhost:3306/nfl_teams
      
   jpa:
     hibernate:
        ddl-auto: none
     show-sql: true
   
   sql:
     init:
       mode: never  
       
    